### ISSUE TITLE
`#TODO`

### ISSUE THREAD

**Issue by NNBnh** [NNBnh/superb-st#1]
- [ ] [Kitty terminal's "Keyboard handling" protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol.html).
- [ ] [Kitty terminal's "Graphics rendering" protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol.html).
- [ ] Session manager that is [Abduco](https://www.brain-dump.org/projects/abduco) + [Scroll](https://tools.suckless.org/scroll) + [`bui-terminal`](https://github.com/NNBnh/bui-terminal) + [Kitty terminal's `scrollback_pager`](https://sw.kovidgoyal.net/kitty/conf.html?highlight=pager#opt-kitty.scrollback_pager).
